# Generated by Django 4.2.6 on 2023-11-13 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemicalSubstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vitriol', 'Vitriol'), ('rebis', 'Rebis'), ('caelum', 'Caelum'), ('hydragenum', 'Hydragenum'), ('vermillion', 'Vermillion'), ('sol', 'Sol'), ('fulgur', 'Fulgur'), ('aether', 'Aether'), ('quebrith', 'Quebrith')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('money', models.FloatField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('difficulty', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('location', models.CharField(max_length=80)),
                ('substance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.alchemicalsubstance')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('novice', 'Novice'), ('journeyman', 'Journeyman'), ('master', 'Master'), ('grandmaster', 'Grandmaster')], max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('formula', 'Alchemy'), ('armor', 'Armor'), ('weapon', 'Weapon')], max_length=20)),
                ('item_crafted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_crafted_by_recipe', to='TheWitcher.item')),
            ],
        ),
        migrations.CreateModel(
            name='AlchemyRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheWitcher.recipe')),
            ],
            bases=('TheWitcher.recipe',),
        ),
        migrations.CreateModel(
            name='CraftRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheWitcher.recipe')),
            ],
            bases=('TheWitcher.recipe',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('characteristic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.character')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.item')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.character')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.characteristic')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='characteristics',
            field=models.ManyToManyField(related_name='characteristic_for_character', through='TheWitcher.CharacterCharacteristic', to='TheWitcher.characteristic'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='skill_for_character', through='TheWitcher.CharacterSkill', to='TheWitcher.skill'),
        ),
        migrations.CreateModel(
            name='CraftRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.craftrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='craftrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredient_for_recipe', through='TheWitcher.CraftRecipeIngredient', to='TheWitcher.item'),
        ),
        migrations.CreateModel(
            name='AlchemyRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.alchemicalsubstance')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.alchemyrecipe')),
            ],
        ),
        migrations.AddField(
            model_name='alchemyrecipe',
            name='substances',
            field=models.ManyToManyField(related_name='substance_for_recipe', through='TheWitcher.AlchemyRecipeIngredient', to='TheWitcher.alchemicalsubstance'),
        ),
    ]
