# Generated by Django 4.2.6 on 2023-10-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='item_crafted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_crafted_by_recipe', to='TheWitcher.item'),
            preserve_default=False,
        ),
    ]
