# Generated by Django 4.2.6 on 2023-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('alchemy_ingredient', 'Alchemy Ingredient'), ('craft_material', 'Craft Material'), ('animals', 'Animals'), ('alchemy_treatment', 'Alchemy Treatment'), ('minerals', 'Minerals')], default='alchemy_ingredient', max_length=20),
            preserve_default=False,
        ),
    ]
