# Generated by Django 4.2.6 on 2023-11-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0002_remove_item_recipe_recipe_item_crafted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlchemyRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheWitcher.recipe')),
                ('vitriol', models.PositiveIntegerField()),
                ('rebis', models.PositiveIntegerField()),
                ('caelum', models.PositiveIntegerField()),
                ('hydragenum', models.PositiveIntegerField()),
                ('vermillion', models.PositiveIntegerField()),
                ('sol', models.PositiveIntegerField()),
                ('fulgur', models.PositiveIntegerField()),
                ('aether', models.PositiveIntegerField()),
                ('quebrith', models.PositiveIntegerField()),
            ],
            bases=('TheWitcher.recipe',),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('formula', 'Alchemy'), ('armor', 'Armor'), ('weapon', 'Weapon')], default='weapon', max_length=20),
            preserve_default=False,
        ),
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='CraftRecipeIngredient',
        ),
        migrations.CreateModel(
            name='CraftRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TheWitcher.recipe')),
                ('ingredients', models.ManyToManyField(related_name='ingredient_for_recipe', through='TheWitcher.CraftRecipeIngredient', to='TheWitcher.item')),
            ],
            bases=('TheWitcher.recipe',),
        ),
        migrations.AlterField(
            model_name='craftrecipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheWitcher.craftrecipe'),
        ),
    ]
