# Generated by Django 4.2.6 on 2024-01-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='+', through='TheWitcher.CraftRecipeIngredient', to='TheWitcher.item'),
        ),
    ]
