# Generated by Django 4.2.6 on 2023-11-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
