# Generated by Django 4.2.6 on 2024-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0003_alter_craftrecipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftrecipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredient_for_recipe', through='TheWitcher.CraftRecipeIngredient', to='TheWitcher.item'),
        ),
    ]
