# Generated by Django 4.2.6 on 2023-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0003_character_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
