# Generated by Django 5.0 on 2024-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0004_alter_craftrecipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('alchemy_ingredient', 'Alchemy Ingredient'), ('craft_material', 'Craft Material'), ('animals', 'Animals'), ('alchemy_treatment', 'Alchemy Treatment'), ('minerals', 'Minerals'), ('alchemy_potion', 'alchemy_potion'), ('weapon', 'Weapon'), ('armor', 'Armor')], max_length=20),
        ),
    ]
