# Generated by Django 5.0 on 2024-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0005_item_description_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('alchemy_ingredient', 'Alchemy Ingredient'), ('craft_material', 'Craft Material'), ('animals', 'Animals'), ('alchemy_treatment', 'Alchemy Treatment'), ('minerals', 'Minerals'), ('alchemy_potion', 'Potion'), ('weapon', 'Weapon'), ('armor', 'Armor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
