# Generated by Django 4.2.6 on 2023-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheWitcher', '0005_recipe_investment_recipe_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('formula', 'Alchemy'), ('ingredient', 'Ingredient'), ('armor', 'Armor'), ('weapon', 'Weapon')], max_length=20),
        ),
    ]
